EcdlModulo:
  actAs: { Timestampable: ~ }
  columns:
    id: { type: integer, primary: true, autoincrement: true, unsigned: true }
    nombre : {type: string(255), notnull: true, unique: true}
    descripcion: {type: text, notnull: true, unique: false}

EcdlPregunta:
  actAs: { Timestampable: ~ }
  columns:
    id: {type: integer, primary: true, autoincrement: true, unsigned: true }
    modulo_id: {type: integer, notnull: true, unsigned: true }
    imagen_id: {type: integer, notnull: false, unsigned: true }
    dificultad: {type: integer, notnull: true, default: 0 }
    texto: {type: text, notnull: true }
  relations:
    EcdlModulo: { onDelete: CASCADE, local: modulo_id, foreign: id, foreignAlias: Modulo }
    EcdlImagen: { onDelete: CASCADE, local: imagen_id, foreign: id, foreignAlias: Imagen }
    
EcdlImagen:
  actAs: { Timestampable: ~ }
  columns:
    id: {type: integer, primary: true, autoincrement: true, unsigned: true }
    imagen: { type: blob, notnull: true }
    
EcdlRespuesta:
  actAs: { Timestampable: ~ }
  columns:
    id: {type: integer, primary: true, autoincrement: true, unsigned: true }
    pregunta_id: {type: integer, notnull: true, unsigned: true }
    texto: {type: text, notnull: true }
    correcta: {type: boolean, notnull: true }
  relations:
    EcdlPregunta: { onDelete: CASCADE, local: pregunta_id, foreign: id, foreignAlias: Pregunta }
    