EcdlModulo:
  actAs: { Timestampable: ~ }
  columns:
    id: { type: integer, primary: true, autoincrement: true, unsigned: true }
    nombre : {type: string(255), notnull: true, unique: true}
    descripcion: {type: text, notnull: true, unique: false}
    
EcdlDificultad:
  actAs: { Timestampable: ~ }
  columns:
    id: { type: integer, primary: true, autoincrement: true, unsigned: true }
    nombre : {type: string(255), notnull: true, unique: true}
    valor: {type: integer, notnull: true, unique: true}
 
EcdlPregunta:
  actAs: { Timestampable: ~ }
  columns:
    id: {type: integer, primary: true, autoincrement: true, unsigned: true }
    modulo_id: {type: integer, notnull: true, unsigned: true }
    imagen: { type: string(255), notnull: true }
    dificultad_id: {type: integer, notnull: true, unsigned: true }
    texto: {type: text, notnull: true }
  relations:
    EcdlModulo: { onDelete: CASCADE, local: modulo_id, foreign: id, foreignAlias: Preguntas }
    EcdlDificultad: { onDelete: CASCADE, local: dificultad_id, foreign: id, foreignAlias: Preguntas }

EcdlRespuesta:
  actAs: { Timestampable: ~ }
  columns:
    id: {type: integer, primary: true, autoincrement: true, unsigned: true }
    pregunta_id: {type: integer, notnull: true, unsigned: true }
    texto: {type: text, notnull: true }
    correcta: {type: boolean, notnull: true }
  relations:
    EcdlPregunta: { onDelete: CASCADE, local: pregunta_id, foreign: id, foreignAlias: Respuestas }
    