<?php

/**
 * EcdlPreguntaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EcdlPreguntaTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object EcdlPreguntaTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('EcdlPregunta');
    }

    public function getPreguntas() {
        $q = $this->createQuery()
                ->from('EcdlPregunta p')
                ->innerJoin('p.EcdlModulo m')
                ->innerJoin('p.EcdlDificultad d')
                ->orderBy('p.created_at');
        return $q;
    }

    public function getRespuestas(int $id_pregunta) {
        $q = $this->createQuery()
                ->from('EcdlRespuesta r')
                ->where('r.pregunta_id = ?', $id_pregunta);

        return $q;
    }

    
}