<?php 

/**
 * EcdlDificultadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EcdlDificultadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EcdlDificultadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EcdlDificultad');
    }
}