<?php

/**
 * EcdlRespuestaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EcdlRespuestaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EcdlRespuestaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EcdlRespuesta');
    }
}