<?php

/**
 * EcdlModuloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EcdlModuloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EcdlModuloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EcdlModulo');
    }
}