<?php

/**
 * EcdlImagenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EcdlImagenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EcdlImagenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EcdlImagen');
    }
}