<?php

/**
 * EcdlPreguntaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EcdlPreguntaTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object EcdlPreguntaTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('EcdlPregunta');
    }

    public function getPreguntas() {
        $q = $this->createQuery()
                ->from('EcdlPregunta p')
                ->innerJoin('p.EcdlModulo m')
                ->innerJoin('p.EcdlDificultad d')
                ->orderBy('p.created_at');
        return $q;
    }

    public function getRespuestas(int $id_pregunta) {
        $q = $this->createQuery()
                ->from('EcdlRespuesta r')
                ->where('r.pregunta_id = ?', $id_pregunta);

        return $q;
    }

    public function getPreguntasXML($modulo_id) {
        $q = $this->createQuery()
                ->from('EcdlPregunta p')
                ->innerJoin('p.EcdlDificultad d')
                ->where('p.modulo_id = ' . $modulo_id);

        return $q->execute();
    }

    public function getPreguntasFiltered($modulo_id, $dificultad_id, $texto) {
        $texto = '%' . str_replace(' ', '%', $texto) . '%';

        $q = $this->createQuery()
                ->from('EcdlPregunta p')
                ->innerJoin('p.EcdlModulo m')
                ->innerJoin('p.EcdlDificultad d')
                ->where('p.texto like ?', $texto);

        if ($modulo_id > 0) {
            $q = $q->andWhere('p.modulo_id = ?', $modulo_id);
        }
        if ($dificultad_id > 0) {
            $q = $q->andWhere('p.dificultad_id = ?', $dificultad_id);
        }
        
        $q = $q->orderBy('modulo_id, dificultad_id');

        return $q;
    }

}