<?php

/**
 * EcdlPreguntaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EcdlPreguntaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EcdlPreguntaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EcdlPregunta');
    }
}