<?php

/**
 * BaseEcdlImagen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property blob $imagen
 * @property Doctrine_Collection $Preguntas
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method blob                getImagen()    Returns the current record's "imagen" value
 * @method Doctrine_Collection getPreguntas() Returns the current record's "Preguntas" collection
 * @method EcdlImagen          setId()        Sets the current record's "id" value
 * @method EcdlImagen          setImagen()    Sets the current record's "imagen" value
 * @method EcdlImagen          setPreguntas() Sets the current record's "Preguntas" collection
 * 
 * @package    EditorPreguntas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEcdlImagen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ecdl_imagen');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             ));
        $this->hasColumn('imagen', 'blob', null, array(
             'type' => 'blob',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EcdlPregunta as Preguntas', array(
             'local' => 'id',
             'foreign' => 'imagen_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}