<?php

/**
 * BaseEcdlRespuesta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $pregunta_id
 * @property text $texto
 * @property boolean $correcta
 * @property EcdlPregunta $EcdlPregunta
 * 
 * @method integer       getId()           Returns the current record's "id" value
 * @method integer       getPreguntaId()   Returns the current record's "pregunta_id" value
 * @method text          getTexto()        Returns the current record's "texto" value
 * @method boolean       getCorrecta()     Returns the current record's "correcta" value
 * @method EcdlPregunta  getEcdlPregunta() Returns the current record's "EcdlPregunta" value
 * @method EcdlRespuesta setId()           Sets the current record's "id" value
 * @method EcdlRespuesta setPreguntaId()   Sets the current record's "pregunta_id" value
 * @method EcdlRespuesta setTexto()        Sets the current record's "texto" value
 * @method EcdlRespuesta setCorrecta()     Sets the current record's "correcta" value
 * @method EcdlRespuesta setEcdlPregunta() Sets the current record's "EcdlPregunta" value
 * 
 * @package    EditorPreguntas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEcdlRespuesta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ecdl_respuesta');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             ));
        $this->hasColumn('pregunta_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             ));
        $this->hasColumn('texto', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('correcta', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EcdlPregunta', array(
             'local' => 'pregunta_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}