<?php

/**
 * BaseEcdlDificultad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $valor
 * @property Doctrine_Collection $Preguntas
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method integer             getValor()     Returns the current record's "valor" value
 * @method Doctrine_Collection getPreguntas() Returns the current record's "Preguntas" collection
 * @method EcdlDificultad      setId()        Sets the current record's "id" value
 * @method EcdlDificultad      setNombre()    Sets the current record's "nombre" value
 * @method EcdlDificultad      setValor()     Sets the current record's "valor" value
 * @method EcdlDificultad      setPreguntas() Sets the current record's "Preguntas" collection
 * 
 * @package    EditorPreguntas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEcdlDificultad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ecdl_dificultad');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('valor', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EcdlPregunta as Preguntas', array(
             'local' => 'id',
             'foreign' => 'dificultad_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}