<?php

/**
 * BaseEcdlPregunta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $modulo_id
 * @property integer $imagen_id
 * @property integer $dificultad
 * @property text $texto
 * @property EcdlModulo $EcdlModulo
 * @property EcdlImagen $EcdlImagen
 * @property Doctrine_Collection $Pregunta
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method integer             getModuloId()   Returns the current record's "modulo_id" value
 * @method integer             getImagenId()   Returns the current record's "imagen_id" value
 * @method integer             getDificultad() Returns the current record's "dificultad" value
 * @method text                getTexto()      Returns the current record's "texto" value
 * @method EcdlModulo          getEcdlModulo() Returns the current record's "EcdlModulo" value
 * @method EcdlImagen          getEcdlImagen() Returns the current record's "EcdlImagen" value
 * @method Doctrine_Collection getPregunta()   Returns the current record's "Pregunta" collection
 * @method EcdlPregunta        setId()         Sets the current record's "id" value
 * @method EcdlPregunta        setModuloId()   Sets the current record's "modulo_id" value
 * @method EcdlPregunta        setImagenId()   Sets the current record's "imagen_id" value
 * @method EcdlPregunta        setDificultad() Sets the current record's "dificultad" value
 * @method EcdlPregunta        setTexto()      Sets the current record's "texto" value
 * @method EcdlPregunta        setEcdlModulo() Sets the current record's "EcdlModulo" value
 * @method EcdlPregunta        setEcdlImagen() Sets the current record's "EcdlImagen" value
 * @method EcdlPregunta        setPregunta()   Sets the current record's "Pregunta" collection
 * 
 * @package    EditorPreguntas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEcdlPregunta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ecdl_pregunta');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             ));
        $this->hasColumn('modulo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             ));
        $this->hasColumn('imagen_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             'unsigned' => true,
             ));
        $this->hasColumn('dificultad', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('texto', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EcdlModulo', array(
             'local' => 'modulo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('EcdlImagen', array(
             'local' => 'imagen_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('EcdlRespuesta as Pregunta', array(
             'local' => 'id',
             'foreign' => 'pregunta_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}