<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/08/19 19:16:26

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ecdl',
  'username' => 'root',
  'password' => 'P4ssw0rd!',
  'port' => 3306,
  'name' => 'doctrine',
)),);
