<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/07/02 19:12:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=192.168.1.14;dbname=ecdl',
  'username' => 'ecdl_user',
  'password' => 'ecdlplay',
  'port' => 3306,
  'name' => 'doctrine',
)),);
