<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/10/29 12:57:54

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ecdl',
  'username' => 'root',
  'password' => 'P4ssw0rd!',
  'name' => 'doctrine',
)),);
